pipeline {
    agent any
    tools {
        maven 'Default'
    }
    stages {
        stage('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('ShowBuildDir') {
            steps {
                sh 'ls -lah'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f mavendemo/pom.xml test'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'mvn -f mavendemo/pom.xml clean package -DskipTests'
            }
            post {
                success {
                    junit 'mavendemo/target/surefire-reports/**/*.xml'
                }
            }
        }
    }
}
